services:
  - type: web
    name: study-ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
      
    startCommand: python manage.py migrate && gunicorn study_assistant.wsgi.application 
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
        sync: false
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: study_assistant_5m10_user
          property: connectionString
databases:
  - name: study_assistant_5m10_user
    plan: free

